// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3U3VfL4d3SrljEl8r5IwE7_NU0vLD0MQ',
    appId: '1:148765587764:web:a630de562cc3bacb61cd61',
    messagingSenderId: '148765587764',
    projectId: 'flutter-pharmacy-app',
    authDomain: 'flutter-pharmacy-app.firebaseapp.com',
    databaseURL: 'https://flutter-pharmacy-app-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-pharmacy-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXytHo3fXW0PzgoM9idqyU6ZtcD_ONh0c',
    appId: '1:148765587764:android:62bfcf9ecd2cd35861cd61',
    messagingSenderId: '148765587764',
    projectId: 'flutter-pharmacy-app',
    databaseURL: 'https://flutter-pharmacy-app-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-pharmacy-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG6rwltSQEmZQpk66Qpp5Z3EwTBae2g4o',
    appId: '1:148765587764:ios:d11b1d866fdc135961cd61',
    messagingSenderId: '148765587764',
    projectId: 'flutter-pharmacy-app',
    databaseURL: 'https://flutter-pharmacy-app-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-pharmacy-app.appspot.com',
    androidClientId: '148765587764-lf7llkeqbaodcie1u15k4jisurj9mbl7.apps.googleusercontent.com',
    iosClientId: '148765587764-0cknqn5g8mpvteinkif7uj8i73dgv7or.apps.googleusercontent.com',
    iosBundleId: 'com.example.newapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDG6rwltSQEmZQpk66Qpp5Z3EwTBae2g4o',
    appId: '1:148765587764:ios:d11b1d866fdc135961cd61',
    messagingSenderId: '148765587764',
    projectId: 'flutter-pharmacy-app',
    databaseURL: 'https://flutter-pharmacy-app-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-pharmacy-app.appspot.com',
    androidClientId: '148765587764-lf7llkeqbaodcie1u15k4jisurj9mbl7.apps.googleusercontent.com',
    iosClientId: '148765587764-0cknqn5g8mpvteinkif7uj8i73dgv7or.apps.googleusercontent.com',
    iosBundleId: 'com.example.newapp',
  );
}
